import {
    APP_PREFIX_PATH,
    CERTIFIER_DASHBOARD_PATH,
    TALLER_DASHBOARD_PATH,
} from '@/constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import { ADMIN, CERTIFIER, SUPPORT, USER } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const appsNavigationConfig: NavigationTree[] = [
    {
        key: 'apps',
        path: '',
        title: 'APPS',
        translateKey: 'nav.apps',
        icon: 'apps',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER, CERTIFIER, SUPPORT],
        subMenu: [
            {
                key: 'apps.project',
                path: '',
                title: 'Project',
                translateKey: 'nav.appsProject.project',
                icon: 'project',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [
                    {
                        key: 'appsSales.dashboard',
                        path: `${APP_PREFIX_PATH}/sales/SalesDashboard`,
                        title: 'Dashboard',
                        translateKey: 'nav.appsProject.dashboard',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'appsgarages_ubication.garages_ubication',
                        path: `${APP_PREFIX_PATH}/garages_ubication`,
                        title: 'Ubicación Negocios',
                        translateKey: 'garages_ubication',
                        icon: '',
                        type: NAV_ITEM_TYPE_COLLAPSE,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'appsUsers.users',
                path: `${APP_PREFIX_PATH}/users`,
                title: 'Usuarios',
                translateKey: 'Usuarios',
                icon: 'user',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, SUPPORT],
                subMenu: [],
            },
            {
                key: 'appsTaller.dashboard',
                path: TALLER_DASHBOARD_PATH,
                title: 'Dashboard',
                translateKey: 'nav.appsTaller.dashboard',
                icon: 'graph',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
            {
                key: 'appsCertifier.dashboard',
                path: CERTIFIER_DASHBOARD_PATH,
                title: 'Dashboard Certificador',
                translateKey: 'Dashboard Certificador',
                icon: 'graph',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [CERTIFIER],
                subMenu: [],
            },
            {
                key: 'appsProfileGarage.profilegarage',
                path: `/profilegarage/:id`, // El placeholder :id será reemplazado
                title: 'Mi Perfil',
                translateKey: 'nav.appsProfileGarage.profilegarage',
                icon: 'user',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
            {
                key: 'appsGarages.garages',
                path: `${APP_PREFIX_PATH}/garages`,
                title: 'Negocios',
                translateKey: 'Negocios',
                icon: 'cars',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, CERTIFIER, SUPPORT],
                subMenu: [],
            },
            {
                key: 'appsServicesList.servicesList',
                path: `${APP_PREFIX_PATH}/services-list`,
                title: 'Lista de Servicios',
                translateKey: 'Lista de Servicios',
                icon: 'servicesList',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            // {
            //     key: 'appsServices.services',
            //     path: `${APP_PREFIX_PATH}/services`,
            //     title: 'Plantillas Servicios',
            //     translateKey: 'Plantillas Servicios',
            //     icon: 'tools',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN],
            //     subMenu: [],
            // },
            {
                key: 'appsCategory.category',
                path: `${APP_PREFIX_PATH}/category`,
                title: 'Categorías',
                translateKey: 'Categorías',
                icon: 'category',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [],
            },
            // {
            //     key: 'appsServicegarage.servicegarage',
            //     path: `${APP_PREFIX_PATH}/serviceGarage`,
            //     title: 'Servicios por Negocio',
            //     translateKey: 'Servicios por Negocio',
            //     icon: 'serviceGarage',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN],
            //     subMenu: [],
            // },
            {
                key: 'appsPlans.plans',
                path: `${APP_PREFIX_PATH}/plans`,
                title: 'Planes',
                translateKey: 'Planes',
                icon: 'plans',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'appsRequestList.requestList',
                path: `${APP_PREFIX_PATH}/requestList`,
                title: 'Solicitudes y servicios solicitados',
                translateKey: 'Solicitudes y servicios solicitados',
                icon: 'requestList',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'appsSubscriptions.subscriptions',
                path: `${APP_PREFIX_PATH}/subscriptions`,
                title: 'Validación e histórico de suscripciones',
                translateKey: 'Validación e histórico de suscripciones',
                icon: 'subscriptions',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [],
            },
            // {
            //     key: 'appsGruas.gruas',
            //     path: `${APP_PREFIX_PATH}/gruas`,
            //     title: 'Histórico de Grúas',
            //     translateKey: 'Histórico de Grúas',
            //     icon: 'gruas',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN],
            //     subMenu: [],
            // },
            {
                key: 'appsVehicleTypes.vehicleTypes',
                path: `${APP_PREFIX_PATH}/vehicle-types`,
                title: 'Tipos de vehículo',
                translateKey: 'Tipos de vehículo',
                icon: 'vehicleTypes',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'appsContact.Puntuacion',
                path: `${APP_PREFIX_PATH}/Puntuacion`,
                title: 'Puntuación de Negocios',
                translateKey: 'Puntuación de Negocios',
                icon: 'Puntuacion',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [],
            },
        ],
    },
]

export default appsNavigationConfig
