import { APP_PREFIX_PATH } from '@/constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import { ADMIN, USER } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const appsNavigationConfig: NavigationTree[] = [
    {
        key: 'apps',
        path: '',
        title: 'APPS',
        translateKey: 'nav.apps',
        icon: 'apps',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
            {
                key: 'apps.project',
                path: '',
                title: 'Project',
                translateKey: 'nav.appsProject.project',
                icon: 'project',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsSales.dashboard',
                        path: `${APP_PREFIX_PATH}/sales/SalesDashboard`,
                        title: 'Dashboard',
                        translateKey: 'nav.appsProject.dashboard',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'apps.garages_ubication',
                        path: `${APP_PREFIX_PATH}/garages_ubication`,
                        title: 'Ubicación Talleres',
                        translateKey: 'garages_ubication',
                        icon: '',
                        type: NAV_ITEM_TYPE_COLLAPSE,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'apps.users',
                path: `${APP_PREFIX_PATH}/users`,
                title: 'Usuarios',
                translateKey: 'Usuarios',
                icon: 'user',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'apps.profileGarage',
                path: `/profilegarage/:id`, // El placeholder :id será reemplazado
                title: 'Mi Perfil',
                translateKey: 'nav.appsProfileGarage.profilegarage',
                icon: 'user',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },
            {
                key: 'apps.garages',
                path: `${APP_PREFIX_PATH}/garages`,
                title: 'Talleres',
                translateKey: 'Talleres',
                icon: 'cars',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'apps.servicesList',
                path: `${APP_PREFIX_PATH}/services-list`,
                title: 'Lista de Servicios',
                translateKey: 'Lista de Servicios',
                icon: 'servicesList',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'apps.services',
                path: `${APP_PREFIX_PATH}/services`,
                title: 'Plantillas Servicios',
                translateKey: 'Plantillas Servicios',
                icon: 'tools',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'apps.category',
                path: `${APP_PREFIX_PATH}/category`,
                title: 'Categorías',
                translateKey: 'Categorías',
                icon: 'category',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'apps.serviceGarage',
                path: `${APP_PREFIX_PATH}/serviceGarage`,
                title: 'Servicios por Taller',
                translateKey: 'Servicios por Taller',
                icon: 'serviceGarage',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'apps.plans',
                path: `${APP_PREFIX_PATH}/plans`,
                title: 'Planes',
                translateKey: 'Planes',
                icon: 'plans',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'apps.subscriptions',
                path: `${APP_PREFIX_PATH}/subscriptions`,
                title: 'Histórico de Subscripciones',
                translateKey: 'Histórico de Subscripciones',
                icon: 'subscriptions',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'apps.paymentValidation',
                path: `${APP_PREFIX_PATH}/paymentValidation`,
                title: 'Validación de pagos',
                translateKey: 'Validación de pagos',
                icon: 'payments',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'apps.ServiceContact',
                path: `${APP_PREFIX_PATH}/ServiceContact`,
                title: 'Servicios Solicitados',
                translateKey: 'Servicios Solicitados',
                icon: 'ServiceContact',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'apps.Puntuacion',
                path: `${APP_PREFIX_PATH}/Puntuacion`,
                title: 'Puntuación de Talleres',
                translateKey: 'Puntuación de Talleres',
                icon: 'Puntuacion',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [],
            },
        ],
    },
]

export default appsNavigationConfig
